## Linear Regression Implementation

We will be solving the house price prediction dataset. Currently as of 2024, Seaborn has deprecated this dataset due to some reasons. Hence, as per the documentation importing the dataset from official website. 

But due to some restrictions feature names were not present. 

In [1]:
# Downloaded dataset from Kaggle as its deperecated from the sklearn.datasets
import pandas as pd

df = pd.read_csv("housing.csv", sep="\s+", header=None)



<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
/var/folders/46/93r9g3kj69s0c5zhwfq5y_s40000gn/T/ipykernel_2203/20638643.py:4: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv("housing.csv", sep="\s+", header=None)


In [2]:
df

0     1      2   3      4      5     6       7   8      9     10  \
0    0.00632  18.0   2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1    0.02731   0.0   7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2    0.02729   0.0   7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3    0.03237   0.0   2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4    0.06905   0.0   2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   
..       ...   ...    ...  ..    ...    ...   ...     ...  ..    ...   ...   
501  0.06263   0.0  11.93   0  0.573  6.593  69.1  2.4786   1  273.0  21.0   
502  0.04527   0.0  11.93   0  0.573  6.120  76.7  2.2875   1  273.0  21.0   
503  0.06076   0.0  11.93   0  0.573  6.976  91.0  2.1675   1  273.0  21.0   
504  0.10959   0.0  11.93   0  0.573  6.794  89.3  2.3889   1  273.0  21.0   
505  0.04741   0.0  11.93   0  0.573  6.030  80.8  2.5050   1  273.0  21.0   

         11    12    13  
0    396.90  4.98  24.0  
1    396.90  9.14  21.6  
2    392.83  4.03  34.7  
3    394.63  2.94  33.4  
4    396.90  5.33  36.2  
..      ...   ...   ...  
501  391.99  9.67  22.4  
502  396.90  9.08  20.6  
503  396.90  5.64  23.9  
504  393.45  6.48  22.0  
505  396.90  7.88  11.9  

[506 rows x 14 columns]

Adding the column names manually.

In [3]:
df.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

In [4]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

Adding a new column "Price" - Dependent variable to the dataset which needs to be predicted.

In [6]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)

target = raw_df.values[1::2, 2]

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/var/folders/46/93r9g3kj69s0c5zhwfq5y_s40000gn/T/ipykernel_2203/1073559601.py:2: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)


In [7]:
df['Price'] = target.data

In [8]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  Price  
0     15.3  396.90   4.98  24.0   24.0  
1     17.8  396.90   9.14  21.6   21.6  
2     17.8  392.83   4.03  34.7   34.7  
3     18.7  394.63   2.94  33.4   33.4  
4     18.7  396.90   5.33  36.2   36.2

Price - Dependent variable or target variable

Remaining all columns - Independent variable

## Importing all the essential libraries

In [9]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Dividing the dataset into independent and dependent features

In [10]:
# Syntax - df.iloc[records/rows, columns]

X = df.iloc[:, :-1] # extracting the independent features

y = df.iloc[:, -1] # extracting the dependent feature

## Importing Linear Regression Library from sklearn

In [11]:
from sklearn.linear_model import LinearRegression # importing linear regression 

# performs lot of combinations of train and test split so that model be will be accuracte
from sklearn.model_selection import cross_val_score 

In [12]:
lin_reg = LinearRegression() # Creating an object

**If the mse is 0, then that means the model is accurate**

In [22]:
# Cross validation performs multiple iterations of train and test splits
# cv = 5 means performs 5 times iterations
mse = cross_val_score(lin_reg, X, y, scoring='neg_mean_squared_error', cv=5)

mean_mse = np.mean(mse)

print(mean_mse)

-1.5433098324241484e-27


## Training the model 

In [17]:
lin_reg.fit(X, y)

LinearRegression()

## Predicting with a new data

In [19]:
lin_reg.predict([[0.00632, 18.0, 2.31, 0, 0.538, 6.575, 65.2, 4.0900, 1, 296.0, 15.3, 396.90, 4.98, 24.0]])

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24.])

## Calculating $\R^2$

In [20]:
lin_reg.score(X, y)

1.0

# Ridge Regression Implementation

In [21]:
from sklearn.linear_model import Ridge

from sklearn.model_selection import GridSearchCV # used for hyperparameter tuning

Creating an object of Ridge library

In [23]:
ridge = Ridge()

1e- 15 means 0.0000000000000001 

1e-10 means 0.000...01 (Ten number of 1's after 1)

In [24]:
params = {'alpha': [1e-15,1e-10,1e-8, 1e-3, 1e-2, 1, 5, 10, 20]}

In [25]:
ridge_regressor = GridSearchCV(ridge, params, scoring='neg_mean_squared_error', cv=5)

Training the model

In [26]:
ridge_regressor.fit(X,y)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

In [30]:
print(ridge_regressor.best_params_) # prints the best alpha

# best score shows the performance of the model
print(ridge_regressor.best_score_) # here in the linear regression we got -1 now we got -2 so Ridge regression is not suitable.

{'alpha': 1e-15}
-2.520742462028078e-28


# Lasso Regression Implementation

In [32]:
from sklearn.linear_model import Lasso

from sklearn.model_selection import GridSearchCV # used for hyperparameter tuning

In [34]:
lasso = Lasso()

In [33]:
params = {'alpha': [1e-15,1e-10,1e-8, 1e-3, 1e-2, 1, 5, 10, 20, 30, 40, 50, 60, 70]}

In [37]:
lasso_regressor = GridSearchCV(lasso, params, scoring='neg_mean_squared_error', cv=5)

In [38]:
lasso_regressor.fit(X, y)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20, 30, 40, 50, 60, 70]},
             scoring='neg_mean_squared_error')

In [41]:
print(lasso_regressor.best_params_) # prints the best alpha

print(lasso_regressor.best_score_) 

{'alpha': 1e-08}
-1.0626085889359316e-07


# Logistic Regression Implementation

In [42]:
from sklearn.linear_model import LogisticRegression

In [43]:
from sklearn.datasets import load_breast_cancer

In [44]:
df = load_breast_cancer()

Independent features

In [45]:
X = pd.DataFrame(df['data'], columns=df['feature_names'])

In [46]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

Dependent features

In [48]:
y = pd.DataFrame(df['target'], columns=['Target'])

In [50]:
y

Target
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

In [52]:
y['Target'].value_counts() 

Target
1    357
0    212
Name: count, dtype: int64

Train Test split

In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=44)

In [55]:
params = [{'C' : [1,5,10]}, {'max_iter': [100, 150]} ]

In [56]:
model = LogisticRegression(C = 100, max_iter=100)

In [57]:
GridSearchCV(model, param_grid=params, scoring='f1', cv=5)

GridSearchCV(cv=5, estimator=LogisticRegression(C=100),
             param_grid=[{'C': [1, 5, 10]}, {'max_iter': [100, 150]}],
             scoring='f1')

In [58]:
model.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=100)

In [61]:
y_pred = model.predict(X_test)

y_pred

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0])

Importing Confusion matrix

In [62]:
from sklearn.metrics import confusion_matrix, classification_report

In [63]:
confusion_matrix(y_test, y_pred)

array([[ 65,   3],
       [  5, 115]])

In [64]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.96      0.94        68
           1       0.97      0.96      0.97       120

    accuracy                           0.96       188
   macro avg       0.95      0.96      0.95       188
weighted avg       0.96      0.96      0.96       188

