## Numpy Library 

Numpy is a powerful library used for mathematical calculations. It is mostly used for multidimensional arrays and one of the most used library for Machine Learning.

Numpy has bindings of C++ language, hence the operations are very fast.

In NumPy all the data is handled in the form of arrays. 

In [4]:
pip install numpy


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


## Array 

Array is a data structute that stores the values of the same data type unlike a list as in python. 

In [1]:
# Importing numpy library

import numpy as np

In [2]:
# Creating an python list
li = [1, 4, 5, 6]

# converting list into array using numpy
arr = np.array(li) 

In [3]:
type(arr) # will show numpy.ndarray

numpy.ndarray

In [4]:
# printing array - Its a One-dimensional array
arr

array([1, 4, 5, 6])

### Using array.shape method

This method describes the array dimension whether its an one-dimensional, two-dimensional, etc.

**Syntax** - array_obj.shape

In [5]:
arr.shape # returns (4,) as its one-dimensional array

(4,)

### Creating two-dimensional array

In [7]:
li1 = [1, 2, 4, 5, 6]
li2 = [4, 5, 6, 7, 8]
li3 = [2, 1, 3, 9, 0]

# creating a two - dimensional array
two_darray = np.array([li1, li2, li3])

two_darray

array([[1, 2, 4, 5, 6],
       [4, 5, 6, 7, 8],
       [2, 1, 3, 9, 0]])

> Trick: In the above cell output, if we clearly observe since its a 2D array, at the start of the array object there were 2 opening brackets ([) and the ending also there were 2 opening brackets. 

Similarly for the 1D array there will be only one opening and one closing bracket. In the same way, the higher the dimension the opening and closing brackets will be the same.

In [9]:
two_darray.shape # Shows (3,5) meaning 3 rows * 5 columns - 2D Array

(3, 5)

### Re-shaping the array

In the earlier cells, we have used the `shape` method where it showed the dimension of the particular array. 

But we can also re-share the array by simply passing the desired shape/dimension we need. 

**Syntax** - array.reshape(no.of rows, no. of cols)

> Remember the total number of elements will not be changed

In [10]:
# Re-shaping the array into (5, 3)

two_darray.reshape(5, 3) 

array([[1, 2, 4],
       [5, 6, 4],
       [5, 6, 7],
       [8, 2, 1],
       [3, 9, 0]])

In [12]:
# Re-shaping the array into (5, 4)

two_darray.reshape(5, 4) # throws an error since the number of elements are not equal

ValueError: cannot reshape array of size 15 into shape (5,4)

In [13]:
# Re-shaping the array into (1, 15)

two_darray.reshape(1, 15) # worked since 1 * 15 = 15 (same number of elements)

array([[1, 2, 4, 5, 6, 4, 5, 6, 7, 8, 2, 1, 3, 9, 0]])

### Indexing

Similar to the list indexing in python

In [15]:
# Creating an one-dimensional array

arr = np.array([23, 45, 67, 89, 25])

In [17]:
# accessing elements using index based technique

print(arr[4])

25


#### Indexing in 2D array 

**Syntax** `twod_array[no_of_rows, no_of_columns]`

> Remember we can also use the slicing technique here to fetch the elements as required

In [19]:
two_darray # printing the 2D array that we have created earlier

array([[1, 2, 4, 5, 6],
       [4, 5, 6, 7, 8],
       [2, 1, 3, 9, 0]])

In [22]:
# Accessing elements from 2D array 

two_darray[:, :] # Since we kept : it considered all the rows and cols

array([[1, 2, 4, 5, 6],
       [4, 5, 6, 7, 8],
       [2, 1, 3, 9, 0]])

In [23]:
# For example, if we want to fetch only [1, 2] from first row and [4, 5] from second row

two_darray[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [26]:
# For example, if we want to fetch only [7, 8] from second row and [9, 0] from third row

two_darray[1:3,3:5]

array([[7, 8],
       [9, 0]])

In [28]:
# Fetch [6,7] and [3,9] from second and third row

two_darray[1:3, 2:4]

array([[6, 7],
       [3, 9]])

In [30]:
# Fetching [5, 6, 7] from second row

two_darray[1, 1:4]

array([5, 6, 7])

### Using np.arange() method

We need to pass the range of the array we require into the `np.arange(start, end, step)` function. This creates a numpy array with the elements as mentioned in the range. 

In [32]:
# Creating an array ranging from 1 to 10 

arr_one = np.arange(0, 10)

arr_one

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# We can also use the step argument

arr_one = np.arange(0, 10, 2)

print(arr_one)

[0 2 4 6 8]


### linspace() method

This method helps us to provide equally divided points between the given range of values. 

We will be mostly using this in Deep learning where we will use if for creating equally divided points quickly using arrays

In [43]:
divided_points = np.linspace(0, 100, 50)

divided_points

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [47]:
# creating an array from 1 to 10
arr = np.arange(1, 11)

print(arr[3:]) # before replacing the values

arr[3:] = 100 # replacing all the values after 3rd index with 100

print(arr)

[ 4  5  6  7  8  9 10]
[  1   2   3 100 100 100 100 100 100 100]


In [52]:
# Assigning the arr to arr1 (new array)

arr1 = arr 

# replacing arr1 elements with 500 after 5th index
arr1[5:] = 500

print(arr1) # printing arr1

print(arr) # If we see clearly, even we performed the operation on arr1 it affected arr since there is a reference

[  1   2   3 100 100 500 500 500 500 500]
[  1   2   3 100 100 500 500 500 500 500]


### copy() method and broadcasting

This method helps us in creating an exact copy of the array, and performing any operations on the newly created array will not affect the old/earlier array

In [54]:
arr1 = arr.copy() # Now creating a copy of arr and storing it in arr1

# performing operations on arr1
arr1[1:] = 20

print(arr1, arr) # If we observe there was no affect to arr array

[ 1 20 20 20 20 20 20 20 20 20] [  1   2   3 100 100 500 500 500 500 500]


### Methods used in Exploratory Data Analysis (EDA)

##### Performing Arithmetic operations

We can simply perform basic arithmetic operations on the array without iterating over the array similar to python list. 

For example, if we want to check the elements which are less than 20 in the array, we can simply do the operation as below

`arr_object < 20` - returns array in form of True and False

Similar to this, we can perform multiple operations like such including divison, remainder, multiplication

In [55]:
arr

array([  1,   2,   3, 100, 100, 500, 500, 500, 500, 500])

In [56]:
# performing less than 50 
arr<50

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [57]:
# if we want the exact numbers which are less than 50 from the array then

arr[arr<50]

array([1, 2, 3])

In [59]:
# performing multiplication
arr * 2

# Similarly we can perform divison, remainder, etc.

array([   2,    4,    6,  200,  200, 1000, 1000, 1000, 1000, 1000])

##### Using `np.ones(value, dtype=int/float)` method

This method prints one's based on the value we passed. By default the ones will be displayed in float datatype, to modify that we need to explicitly change the datatype to 'int'

In [62]:
print(np.ones(10)) # prints all ones in float datatype

print(np.ones(10, dtype=int)) # prints in int datatype

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [64]:
# printing ones in two dimensional array

print(np.ones([2,5], dtype=int))

[[1 1 1 1 1]
 [1 1 1 1 1]]


##### Print Random values 

We can use multiple functions which are part of random class like 

`random.rand()` - gives random values in given shape

`random.randn()` - gives random values in standard normal distribution

`random.randint()` - gives integer values as per the given range

`random.random_sample()` - provides random values between 0 and 1 in the given shape.


In [66]:
np.random.rand(2, 4) # random values in given shape

array([[0.44273135, 0.91233482, 0.40582049, 0.92192369],
       [0.10769547, 0.51387653, 0.4444384 , 0.1134224 ]])

In [67]:
np.random.randn(3, 5) #Return a sample (or samples) from the "standard normal" distribution.

array([[ 0.01692048,  0.32691392,  0.76199817, -0.50760124,  1.07738217],
       [-1.1581851 , -0.47807832,  1.07789881,  0.97798277,  0.71137287],
       [-0.14253159, -0.20106364,  0.23286259,  0.16725101,  0.22874007]])

In [78]:
np.random.randint(10, 100,8).reshape(4,2) # returns values ranging from low to high along with the size 

array([[87, 58],
       [58, 63],
       [65, 93],
       [40, 73]])

In [81]:
np.random.random_sample(10) # Return random floats in the half-open interval [0.0, 1.0) as per the given size.

array([0.99838634, 0.18748798, 0.41248967, 0.42202119, 0.15682951,
       0.85625196, 0.02152887, 0.83431489, 0.15593716, 0.28076599])